language: python
services:
  - postgresql
python:
  - 2.7
install:
  - pip install -r dev-requirements.txt
before_script:
  - psql -c 'create database capomastro;' -U postgres
  - cp capomastro/local_settings.py.example capomastro/local_settings.py
  - sed -i -e 's/getpass\.getuser()/\"postgres\"/g' capomastro/local_settings.py
  - python manage.py migrate --noinput
script:
  - python manage.py test
